version: "3.7"
services:
# docker run -dp 3000:3000 \
# --network net0 
# -e MYSQL_HOST=mysql \
# -e MYSQL_USER=root \
# -e MYSQL_PASSWORD=123 \
# -e MYSQL_DB=todos \
# app:latest

# docker run -dp 3306:3306 \
# -e MYSQL_ROOT_PASSWORD=123 \
# -e MYSQL_DATABASE=todos \
# --network net0 --network-alias mysql \
# mysql:5.7

  app:
    image: myapp:latest
    ports: 
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
    - /mysql-data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: 123
       MYSQL_DATABASE: todos


       